# Generated by Django 5.0.1 on 2024-01-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lesson_delete_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
