# Generated by Django 5.0.1 on 2024-01-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('article', 'Article')], default='article', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
    ]
