# Generated by Django 5.0.1 on 2024-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('article', 'Article')], default='article', max_length=20),
        ),
    ]
