# Generated by Django 5.0.1 on 2024-02-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_quiz_options_lesson_youtube_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('article', 'Article')], default='article', max_length=20),
        ),
    ]
