# Generated by Django 5.0.1 on 2024-02-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('quiz', 'Quiz')], default='article', max_length=20),
        ),
    ]
